/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     0

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x60, 0xC5, 0xA8

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                          { IEEE_OUI, 0xCD, 0x03, 0x14, 0xD0, 0x31 }

/*!
 * Application IEEE EUI (big endian)
 */
#define LORAWAN_APPLICATION_EUI                     { 0x23, 0xBD, 0xDF, 0xBE, 0x10, 0xD0, 0x75, 0x68 }
                                                     //70 b3 d5 7e f0 00 46 a4      70 B3 D5 7E D0 00 7D FA
/*!
 * AES encryption/decryption cipher application key
 */
#define LORAWAN_APPLICATION_KEY                     { 0xAB, 0x11, 0xE9, 0xE6, 0xF4, 0xB1, 0xDF, 0x1A, 0x7E, 0xFF, 0x18, 0x16, 0x6B, 0x3F, 0xEB, 0xAA }
                                                     //a6b08140dae1d795ebfa5a6dee1f4dbd    09A503D6256F9EF612A15181F583880A
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x260114BE

/*!
 * AES encryption/decryption cipher network session key
 */
                                                      //B0    18    91    C1    72    F8    A3    01    52    A4    75    10    C9    2A    E1    1F
#define LORAWAN_NWKSKEY                             { 0xB0, 0x18, 0x91, 0xC1, 0x72, 0xF8, 0xA3, 0x01, 0x52, 0xA4, 0x75, 0x10, 0xC9, 0x2A, 0xE1, 0x1F }

/*!
 * AES encryption/decryption cipher application session key
 */
                                                     // B5    A6    22    5C    CA    74    91    69    21    5D    7A    23    50    51    6B    12
#define LORAWAN_APPSKEY                             { 0xB5, 0xA6, 0x22, 0x5C, 0xCA, 0x74, 0x91, 0x69, 0x21, 0x5D, 0x7A, 0x23, 0x50, 0x51, 0x6B, 0x12 }

#endif // __LORA_COMMISSIONING_H__
